### ISSUE TITLE
Some Typo's in your keygen scripts.

### ISSUE THREAD

**Issue by mrdude2478** [borntohonk/Switch-Ghidra-Guides#10]
In both keygen files, you need to change to the following:

import argeparse

change to

import argparse

Also in the file: scripts/erista_keygen.py, you have an error on the path on line 21

```
subprocess.run(f'hactoolnet --keyset prod.keys -t pk11 0100000000000819/romfs/nx/package1 --outdir 0100000000000819/romfs/nx/pkg1', stdout = subprocess.DEVNULL)
```

Change to:
```
subprocess.run(f'hactoolnet --keyset prod.keys -t pk11 0100000000000819/romfs/a/package1 --outdir 0100000000000819/romfs/nx/pkg1', stdout = subprocess.DEVNULL)
```

Modding both files fixes errors - you could also add a python requirements.txt , If not, users should run - "pip install argparse" to install that module to python.

Thanks for the keygens though, they work well.

**Comment by borntohonk** [comment]
> Change to:
> 
> ```
> subprocess.run(f'hactoolnet --keyset prod.keys -t pk11 0100000000000819/romfs/a/package1 --outdir 0100000000000819/romfs/nx/pkg1', stdout = subprocess.DEVNULL)
> ```

This actually is not broken.

/a/ is for mariko.

/nx/ is for erista, the reason it's failing is because you do not have the appropriate keys.

the keys required are descriped in the README.md, but the tl:dr really is you need tsec_secret_26 to derive package1_key_%% beyond 6.2.0, and tsec_secret_26 requires hardware glitching of the tsec aes scp key register and bruteforcing.


here's some reading material if you are interested in that, combined its all relevant, but plutoo's gist is what is required:

https://gist.githubusercontent.com/plutooo/733318dbb57166d203c10d12f6c24e06/raw/15c5b2612ab62998243ce5e7877496466cabb77f/tsec.txt
https://hexkyz.blogspot.com/2021/11/je-ne-sais-quoi-falcons-over-horizon.html
https://www.unknowncheats.me/forum/3141470-post1.html
https://github.com/vbe0201/faucon
https://github.com/CAmadeus/falcon-tools
https://gitlab.com/Nxyoom/tsec-exploration

```
Python script to derive entire keyset for the firmware version you've input, requires "package1_key_%%" and "tsec_root_key_%%" to be present already. (requires tsec_secret_26)
    * It will obtain the key source referred to as "master_kek_source_%%" from the firmware files you've provided, and then initiate key derivation if needed and replace your existing "prod.keys". *
    * This script eliminates the need for "lockpick" of any kind, assuming the user already have the pre-requisite keys.
    * This script works by extracting "package1" with the "package1_key_%%", and then proceeds in finding "master_kek_source_%%", appending that to your existing prod.keys as defined in [Part 2](guides/Part2.MD) of the guides. And then transforms "master_kek_source_%%" using "tsec_root_key_%%" to become "master_kek" and subsequently sets off the key derivation chain, using the tool "hactoolnet".
    * Usage: do "python scripts/erista_keygen.py -f folder / --firmware folder" with firmware files present in a folder called firmware, or as supplied with -f or --firmware . [
    ```

**Comment by borntohonk** [comment]
I am considering pushing a smaller writeup on this, but it is one of my low-priority side-projects.

ideally i'd figure out how to rebase it to mainline hekate as it has features for this and better code to amend. (i currently use a hwinit based launcher, using the gplv2 example from https://gitlab.com/Nxyoom/tsec-exploration/-/tree/main/launcher )

**Comment by mrdude2478** [comment]
Nice, thanks for the info. I've just made a test c# keygen app now and it seems to work fine, so far I have this:

hactoolnet --keyset decrypt.keys -t switchfs Firmware --title 0100000000000819 --romfsdir 0100000000000819/romfs/
hactoolnet --keyset decrypt.keys -t pk11 0100000000000819/romfs/a/package1 --outdir 0100000000000819/romfs/a/pkg1

decrypt.keys at this point only has:
mariko_bek = 6Axxxxx
mariko_kek = 41xxxxx

At this point when we can see the OEM Bootloader Version:

example:
Firmware 15.xx - OEM Bootloader Version:      0F (mariko_master_kek_source_0E)
Firmware 16 - OEM Bootloader Version:         10 (mariko_master_kek_source_0F)
Firmware 17 - OEM Bootloader Version:         11 (mariko_master_kek_source_10)
Firmware 18 - OEM Bootloader Version:         12 (mariko_master_kek_source_11)

Now we can write to our decrypt.keys - mariko_master_kek_source_(OEM Bootloader Version -0x1) = xxx

I wrote the program to get the key from Decrypted.bin automatically and append decrypt.keys, so now we can run hactool to output prod.keys with the new values added.

hactoolnet --keyset "decrypt.keys" -t keygen > prod.keys

I actually wrote a program called IPS Patch creator ages ago that can decrypt the switch firmware if you know the keys, and now I have this info for the keygen I can add this keygen code into it so that it can decrypt the firmware automatically without needing to update the keys manually. So thanks for your scripts are they we very helpfull in understanding how these keys are derived.

**Comment by borntohonk** [comment]
> I actually wrote a program called IPS Patch creator ages ago that can decrypt the switch firmware if you know the keys, and now I have this info for the keygen I can add this keygen code into it so that it can decrypt the firmware automatically without needing to update the keys manually. So thanks for your scripts are they we very helpfull in understanding how these keys are derived.

yeah, i actually wrote the means to automatically update using mariko bek/kek, because the mariko package is always accessible with keys from a lower iteration because it is required for firmware updates, so initiating keygen while processing firmware files ensures you always have the latest mariko_master_kek_source which also ensures you will always have the latest mariko_master_kek, which in turn will provide you the latest master_key, etc etc

**Comment by mrdude2478** [comment]
This is nice to have information. I am so glad you posted those scripts as they make life alot easier without needing to update lockpic_rcm now. Before I was needing to wait until Atmosphere git was updated so I could get the keys to update that but now I don't need to anymore. This makes writing patches much faster now as I can dump FW as soon as it's available and then decrypt it, then use ghidra to dump decrpyted modules into c code - which makes it so much easier to trace the sub's where to patch if that patterns I normally use change. I am pretty chuffed I came across your git yesterday as I have learned alot from it.

Cheers.

**Comment by borntohonk** [comment]
no problem mate

**Comment by mrdude2478** [comment]
PS. I know the Bootloader Version is shown in hactoolnet output, but for speed in code it seems to be at header address 0x150 in /0100000000000819/romfs/a/package1. For your scripts you can read address and use it to write mariko_master_kek_source_xx without having a prod.keys file first and then you can just generate a brand new file from scratch without appending anything.

**Comment by borntohonk** [comment]
> PS. I know the Bootloader Version is shown in hactoolnet output, but for speed in code it seems to be at header address 0x150 in /0100000000000819/romfs/a/package1. For your scripts you can read address and use it to write mariko_master_kek_source_xx without having a prod.keys file first and then you can just generate a brand new file from scratch without appending anything.

I actually was just about to push a commit with that, as when i first made it it was lazily done.

**Comment by mrdude2478** [comment]
Thanks for updating your scripts, the new updated ones are better and work well. I've been busy all day but I'll have a look in a while and see if I can find anything else that could, but all seems good now on my end - from a noobs perspective :-).
