### ISSUE TITLE
Slight adjustment to keygen scripts - for keys path.

### ISSUE THREAD

**Issue by mrdude2478** [borntohonk/Switch-Ghidra-Guides#11]
In lines 19 + 21

```
subprocess.run(f'hactoolnet --keyset prod.keys -t switchfs {firmware} --title 0100000000000819 --romfsdir 0100000000000819/romfs/', stdout = subprocess.DEVNULL)

and

subprocess.run(f'hactoolnet --keyset prod.keys -t pk11 0100000000000819/romfs/nx/package1 --outdir 0100000000000819/romfs/nx/pkg1', stdout = subprocess.DEVNULL)
```

This could be adjusted to:
```
subprocess.run(f'hactoolnet --keyset ' + prod_keys + ' -t switchfs {firmware} --title 0100000000000819 --romfsdir 0100000000000819/romfs/', stdout = subprocess.DEVNULL)

and

subprocess.run(f'hactoolnet --keyset ' + prod_keys + ' -t pk11 0100000000000819/romfs/a/package1 --outdir 0100000000000819/romfs/nx/pkg1', stdout = subprocess.DEVNULL)
```

Reason, well you already define the path to check in this line:  prod_keys = os.path.expanduser('~/.switch/prod.keys')
When the subprocess runs it now looks where you put the prod_keys check in the first place.

Thanks.

**Comment by borntohonk** [comment]
> In lines 19 + 21
> 
> ```
> subprocess.run(f'hactoolnet --keyset prod.keys -t switchfs {firmware} --title 0100000000000819 --romfsdir 0100000000000819/romfs/', stdout = subprocess.DEVNULL)
> 
> and
> 
> subprocess.run(f'hactoolnet --keyset prod.keys -t pk11 0100000000000819/romfs/nx/package1 --outdir 0100000000000819/romfs/nx/pkg1', stdout = subprocess.DEVNULL)
> ```
> 
> This could be adjusted to:
> 
> ```
> subprocess.run(f'hactoolnet --keyset ' + prod_keys + ' -t switchfs {firmware} --title 0100000000000819 --romfsdir 0100000000000819/romfs/', stdout = subprocess.DEVNULL)
> 
> and
> 
> subprocess.run(f'hactoolnet --keyset ' + prod_keys + ' -t pk11 0100000000000819/romfs/a/package1 --outdir 0100000000000819/romfs/nx/pkg1', stdout = subprocess.DEVNULL)
> ```
> 
> Reason, well you already define the path to check in this line: prod_keys = os.path.expanduser('~/.switch/prod.keys') When the subprocess runs it now looks where you put the prod_keys check in the first place.
> 
> Thanks.

I instead added argument -k or --keys to provide a keyfile, but still default to ~/.switch/prod.keys if the user does not provide an input.

**Comment by borntohonk** [comment]
well did more than what you asked for, also with python, doing a "formatted string", you can encapsule variables with squiggly brackets to run them as code instead of doing  'thing' + other_thing + 'thing`
```py
subprocess.run(f'hactoolnet -t switchfs {location} --title 0100000000000819 --romfsdir {location}/titleid/0100000000000819/romfs/', stdout = subprocess.DEVNULL)
```

**Comment by mrdude2478** [comment]
Yep, thanks - I also made a type in the above. I meant to type:

"subprocess.run(f'hactoolnet --keyset ' + keyset,' -t switchfs {firmware} --title 0100000000000819 --romfsdir 0100000000000819/romfs/', stdout = subprocess.DEVNULL)"

My bad, but you fixed it anyway :-).
