### ISSUE TITLE
Mod clean up used files.

### ISSUE THREAD

**Issue by mrdude2478** [borntohonk/Switch-Ghidra-Guides#13]
After the keygen has worked, clean up 0100000000000819 folder and all it's contents:

Solution: Install shutils module - pip install shutils

In keygen file at top add: import shutil
After line: print(f'# Keygen completed and output to {prod_keys}, exiting.')

Add these two lines:
decrypted_bin.close()
shutil.rmtree('0100000000000819')

Now once the keygen has completed its task these temp files will be removed.

**Comment by borntohonk** [comment]
shutil is a native thing in modern python 3, so that's not problematic to add, but i will address this alongside other stuff in another commit
