### ISSUE TITLE
hactoolnet question

### ISSUE THREAD

**Issue by pgalonza** [borntohonk/Switch-Ghidra-Guides#16]
Hi, i am studying the key generation scripts and see a difference in the commands for revisions.
V1
hactoolnet --keyset {prod_keys} -t pk11 0100000000000819/romfs/nx/package1 --outdir 0100000000000819/romfs/nx/pkg1
V2
hactoolnet --keyset temp.keys -t pk11 0100000000000819/romfs/a/package1 --outdir 0100000000000819/romfs/a/pkg1

I use key file from public source and for Mariko command work good, but for Erista i only get metadata about package1 to stdout and thats all.

**Comment by borntohonk** [comment]
Erista requires tsec csecret 26, which means of obtaining is not public, only thing public is a writeup by plutoo, which involves voltage glitching the scp aes encryption mechanic of csigenc of a csecret with lower than 0x3, and collecting partial aes samples of a few thousand and then bruteforcing the real key from the partials.

Ignore it, it's not for you.
