### ISSUE TITLE
FS patch3 - FW19

### ISSUE THREAD

**Issue by mrdude2478** [borntohonk/Switch-Ghidra-Guides#19]
I see you have added a new patch for FW19 for the fat/exfat fs.

patch3 = '%06X%s%s' % (result2.start() - 0x84, '0004', '10000014') #

I have XCI and NSP working without that patch (just using the same patches as before), NRO forwarders are not working for now even with your new patch, what is this new patch meant to do? I am just interested in why it exists? I know it's a branch to a new address but is it for NRO forwarders?

Maybe AtmosphereNX needs finished and this is why they are not working for now?

**Comment by borntohonk** [comment]
> I see you have added a new patch for FW19 for the fat/exfat fs.
> 
> patch3 = '%06X%s%s' % (result2.start() - 0x84, '0004', '10000014') #
> 
> I have XCI and NSP working without that patch (just using the same patches as before), NRO forwarders are not working for now even with your new patch, what is this new patch meant to do? I am just interested in why it exists? I know it's a branch to a new address but is it for NRO forwarders?
> 
> Maybe AtmosphereNX needs finished and this is why they are not working for now?

Are you sure you're on 19.0.0? Because unless you're compiling atmosphere yourself or running the build from the reswitched discord, how could you tell? :)

![1728553318330661](https://github.com/user-attachments/assets/dedcb213-ccd3-42f7-9806-9cb836eae7e6)

![1728553457959450](https://github.com/user-attachments/assets/24bde6b2-b5c6-4daf-a51f-0e23dedc6d2c)

**Comment by borntohonk** [comment]
This is what the patch 2 and patch 3 does.

![1728563887254942](https://github.com/user-attachments/assets/61395fe6-bb76-4b6a-8824-2a67d81d0d0c)

**Comment by borntohonk** [comment]
there's also a second CMP added togheter with the B.EQ which checks the value of TST w0,#0xFF, inside of the existing old instruction block, which goes back and forth, it gets confusing, but that is why the "third value" is patched now.

![1728553318330661](https://github.com/user-attachments/assets/3515795c-8eeb-4963-a700-f78f73ff1e8f)

**Comment by borntohonk** [comment]
> I have XCI and NSP working without that patch

Also to add to this......

modern day "xci installs" are signature intact and not byteflipped to eshop, thus don't need the nca header patch, nor atmosphere loader patch, only ES is required for "NSP" sourced from eshop.

forwarders ("homebrew signed installed binaries") require both the loader patch **AND** all patches to FS. So the reason you have things working and assume nothing is wrong, is more of just coincidence. 

the difference is that homebrew signed binaries are not only signature broken, they are custom signed.


"xci installs" that are "converted" (byteflipped source to digital in header using bad converters), or repackaged .nca's require all patches.

**Comment by borntohonk** [comment]
also...

https://github.com/Atmosphere-NX/Atmosphere/compare/master...1900_support#diff-8f4f075aef2c24447ccda4c26924401ac8ee494eb948d971e1116e8df73bda07R433


```
 /* 19.0.0+ disallows more than one flag set; we are always DebugMode for kernel, so ForceDebug is the most powerful/flexible flag to set. */
 ```


to me it seems like a loader permission issue, related to this, which will require a fork / new loader patch

**Comment by borntohonk** [comment]
@mrdude2478 
https://github.com/switchbrew/nx-hbloader/blob/master/hbl.json#L246-L250

the code which all forwarders are based off of sets two debug flags, which is disallowed now...

So yeah, uhm, yup. All forwarders, homebrew, etc will need to be recompiled with only one debug flag set.

feel free to comment further, i will respond, but i consider this investigated enough from my end.

```json
            "type": "debug_flags",
            "value": {
                "allow_debug": false,
                "force_debug_prod": false,
                "force_debug": true
            }
```

**Comment by mrdude2478** [comment]
Thanks for the detailed information, It will take me a while to get through investigating all that and I only had 3 hours sleep last night so I'll probably do that tomorrow.

I compiled the 1900_support branch and modded fusee to be able use IPS patches as sys-patch doesn't apply any patches (I recompiled that as well) and Hekate was causing a yellow screen so maybe needs updating as well for 19.0 fw and new.

I used the "test" AtmosphereNX files that were posted on the discord server (apart from the modded fusee.bin) .

Anyway, thanks for replying, you have given a great deal of info for me to get through and have been most helpful.

**Comment by borntohonk** [comment]
> I guess you are correct in that forwarders will need redone and I had a look at sys-patch code and debug flags are set like this:

```c++
            "type": "debug_flags",
            "value": {
                "allow_debug": false,
                "force_debug_prod": false,
                "force_debug": true
            }
```


with this commit for switch-tools https://github.com/switchbrew/switch-tools/pull/47/files

**Comment by borntohonk** [comment]
and also to re-iterate, the third new patch is not done because it "does something", it's done because it's new and called from externally outside this function, and and whatever value sent to it's TST #0xFF value when called for, can prematurely cockblock the other patch, since it's before the other one.

I see what it does, i know what it does, i know it's not ran automatically in this specific function, but it's a variable that can be set outside, so the logical thing to do, is to patch it to never be able to be called for that way.

it is patched so that whatever is external calling for this very clearly signature checking function, does not pass a value that fails the race condition, because games and other modules can do that, it's calling for a fatal/fail, which is not wanted.

control what you can control, letting it be unpatched is unwanted behavior.

**Comment by mrdude2478** [comment]
Very interesting. Also thanks for posting the commit to switch tools. I'm going to have a look at that patch again now that you have explained in a lot of detail. I was pretty tired yesterday so couldn't think straight but now I read again what you posted it makes more sense.

Thanks again.

**Comment by borntohonk** [comment]
> Very interesting. Also thanks for posting the commit to switch tools. I'm going to have a look at that patch again now that you have explained in a lot of detail. I was pretty tired yesterday so couldn't think straight but now I read again what you posted it makes more sense.
> 
> Thanks again.

diffing the functions responsible for calling the responsible function

18.1.0 calling for FUN_741F0 (function we change to mov x0, xzr):
FUN_72710
FUN_74530
FUN_74AA0


19.0.0 calling for FUN_743F0 (function we change to mov x0, xzr):
FUN_722A0 (1 cmp less than 18.1.0 before calling FUN_743F0)
FUN_74750 (1 cmp less than 18.1.0 before calling FUN_743F0)
FUN_74D00 (similar to 18.1.0)

and in 19.0.0 in FUN_743F0 we now have a new cmp of tst 0xFF, not by coincidence i assume! Before i assume said cmp would not really fail, and now it has an actual fail condition. What exactly its calling for i'm not going to put much time into investigating

**Comment by borntohonk** [comment]
I basically am not very trusting of the new value, one can generally get a good idea of how things work by utilizing the graph functionality of ghidra, and if one is not familiar with what instructions do what, one can use arm's documentation https://developer.arm.com/documentation/
![graph](https://github.com/user-attachments/assets/a3d42989-d38e-43fd-957c-e63f7054e17b)

**Comment by borntohonk** [comment]
hmm i just made the realization that we end with a NOP inside of FUN_7100076AC0, lmao

**Comment by mrdude2478** [comment]
> hmm i just made the realization that we end with a NOP inside of FUN_7100076AC0, lmao
> 
> in other words the mov 0x, xzr ensures we hit that TBNZ condition with a zero NOP'ing the chain and do not go down to the 0x200 test.

I use IDAPro, it also has graphing feature and when you change the hex in the program to the new patch, it shows the new graph and the address to where the branch is made. I can post you a link for the 9.0.240807 version - fully activated if you want to try it.

**Comment by borntohonk** [comment]
> when you change the hex in the program to the new patch, it shows the new graph and the address to where the branch is made. 
Ghidra lets you patch instructions and it also renews the graph, as well as pseudocode live.
