### ISSUE TITLE
uncompressed_nifm.nso0 is not output

### ISSUE THREAD

**Issue by lsp199308** [borntohonk/Switch-Ghidra-Guides#8]
python firmware_organizer.py，uncompressed_nifm.nso0 is not output
In 010000000000000F, there are only main and Program.nca

**Comment by borntohonk** [comment]
> python firmware_organizer.py，uncompressed_nifm.nso0 is not output In 010000000000000F, there are only main and Program.nca

13.10.2022            firmware
13.10.2022    1335848 compressed_exfat.kip1
13.10.2022    1299340 compressed_fat32.kip1
13.10.2022       4990 firmware_organizer.py
13.10.2022     932816 uncompressed_es.nso0
13.10.2022    2561808 uncompressed_exfat.kip1
13.10.2022    2507776 uncompressed_fat32.kip1
13.10.2022    1151544 uncompressed_nifm.nso0

I cannot reproduce your issue with the current master.
